[project]
name = "shopkeeper-agent-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "asyncmy>=0.2.11",
    "cryptography>=47.0.0",
    "elasticsearch[async]>=8,<9",
    "fastapi[standard]>=0.128.8",
    "huggingface-hub>=1.8.0",
    "jieba>=0.42.1",
    "langchain>=0.3.28",
    "langchain-deepseek>=0.1.4",
    "langchain-huggingface>=0.3.1",
    "langgraph>=0.6.11",
    "loguru>=0.7.3",
    "omegaconf>=2.3.0",
    "pyyaml>=6.0.3",
    "qdrant-client>=1.16.1",
    "sqlalchemy>=2.0.49",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
